-- One TOTP authenticator per user. Keyed by username for the demo; use an immutable user ID in production.
create table totp_credential (
    username            varchar(255)             not null primary key,
    encrypted_secret    varchar(512)             not null,  -- AES-256-GCM "<keyId>:<Base64>", never the raw secret
    created_at          timestamp with time zone not null,
    confirmed_at        timestamp with time zone,           -- NULL while enrollment is pending
    last_used_time_step bigint                              -- replay protection: only later steps are accepted
);

-- Single-use recovery codes, stored as salted Argon2id hashes.
create table recovery_code (
    id         bigint generated by default as identity primary key,
    username   varchar(255)             not null,
    code_hash  varchar(255)             not null,
    created_at timestamp with time zone not null,
    used_at    timestamp with time zone                     -- NULL until consumed
);

create index recovery_code_by_username on recovery_code (username);
