-- Applied by Spring Boot on startup (embedded database). In production, manage the schema with
-- Flyway or Liquibase and keep spring.jpa.hibernate.ddl-auto=validate.
create table user_account (
    id            bigint generated by default as identity primary key,
    email         varchar(320)                not null,
    -- Self-describing hash such as {argon2}$argon2id$v=19$m=19456,t=2,p=1$<salt>$<hash>
    password_hash varchar(255)                not null,
    created_at    timestamp(6) with time zone not null,
    constraint uk_user_account_email unique (email)
);
